### ISSUE TITLE
check.cgi giving error 102032 when Wii Number starts with 0

### ISSUE THREAD

**Issue by larsenv** [WiiLink24/Mail-Server#2]
I'm not part of RiiConnect24 anymore, however when I tried to add my friend to the Wii he was getting error 102032. Upon further inspection by recreating the challenge response, the issue seems to be because the hash is calculated without padding the Wii Number with 16 zeroes. Therefore, anyone that connects with a Wii Number starting with 0 will get 102032 because the Wii Number in the challenge response is being calculated without the padding.

**Comment by Gamebuster19901** [comment]
I am getting error 102032 and 110250 when attempting to send wii mail from my wii (original hardware). It seems related to this issue.

Please let me know what information you need to help debug this issue.

![image](https://github.com/WiiLink24/Mail-Server/assets/7155747/1259f466-f6ec-43cd-9a2c-af7add593f49)

**Comment by larsenv** [comment]
This number starts with 0, so whatever @noahpistilli did in the latest commit as his fix actually has broke it, it needs to properly be fixed - cc @Naim2000

**Comment by Gamebuster19901** [comment]
I recommend adding some unit tests to the project to help detect issues like this before they hit production.

**Comment by noahpistilli** [comment]
> This number starts with 0, so whatever @noahpistilli did in the latest commit as his fix actually has broke it

It was broken before, this fixed it however numbers in the database are stored without the 0 which is why it thinks this user's number doesn't exist. I will work on a database fix for this.
